name: discipline_app
description: "A custom offline habit tracking and discipline app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
